"""
Statement-cycle boundaries for the Shared Expenses tab.

A "month" in Shared Expenses is NOT a calendar month -- it's the joint
credit card's statement cycle, because that's what actually determines
which charges land on the bill the household settles up on. Using
calendar bounds put transactions in the wrong month relative to the card
statement, so the household switched to statement cycles mid-2026.

Two eras, split at CYCLE_TRANSITION:

1. Before the switch, cycles WERE calendar months (Dec 2025 - Jun 2026),
   plus one short transition cycle (Jul 2026 = 7/1 - 7/13) that closes
   out the old scheme. Those are reproduced here rather than recomputed
   so historical months keep matching the numbers already settled in the
   spreadsheet -- don't "fix" a past cycle, it would silently restate a
   month someone already paid.

2. From CYCLE_TRANSITION onward, cycles are generated by the rule the
   statement actually follows:
       start = previous cycle's end + 1 day
       end   = start + (number of days in the LABELED month) - 1
   i.e. the cycle labeled "September 2026" is 30 days long because
   September has 30 days, and it runs 8/14 - 9/12. This walks the
   boundary backward through the calendar a little each month, which is
   exactly what the real statement dates do.

Only an anchor date is stored, not a table of dates, so future cycles
keep generating without anyone hand-maintaining a list.
"""
import calendar
import datetime

# First cycle generated by the statement-cycle rule, and the date it
# starts (= the day after the Jul 2026 transition cycle ends).
CYCLE_TRANSITION = (2026, 8)
CYCLE_TRANSITION_START = datetime.date(2026, 7, 14)

# Pre-transition cycles that aren't plain calendar months. Everything
# else before CYCLE_TRANSITION falls back to the calendar month.
CYCLE_OVERRIDES: dict[tuple[int, int], tuple[datetime.date, datetime.date]] = {
    (2026, 7): (datetime.date(2026, 7, 1), datetime.date(2026, 7, 13)),
}


def _month_index(year: int, month: int) -> int:
    """Comparable ordinal for a (year, month) pair, so cycles can be
    ordered without constructing dates."""
    return year * 12 + (month - 1)


def _next_month(year: int, month: int) -> tuple[int, int]:
    return (year + 1, 1) if month == 12 else (year, month + 1)


def _calendar_month(year: int, month: int) -> tuple[datetime.date, datetime.date]:
    return (
        datetime.date(year, month, 1),
        datetime.date(year, month, calendar.monthrange(year, month)[1]),
    )


def get_cycle(year: int, month: int) -> tuple[datetime.date, datetime.date]:
    """Inclusive [start, end] dates of the statement cycle labeled
    `month` of `year`."""
    if (year, month) in CYCLE_OVERRIDES:
        return CYCLE_OVERRIDES[(year, month)]

    if _month_index(year, month) < _month_index(*CYCLE_TRANSITION):
        return _calendar_month(year, month)

    # Walk forward from the anchor. Bounded by the year range the API
    # accepts (2000-2100), so this is at most a few hundred iterations.
    cursor_year, cursor_month = CYCLE_TRANSITION
    start = CYCLE_TRANSITION_START
    while True:
        length = calendar.monthrange(cursor_year, cursor_month)[1]
        end = start + datetime.timedelta(days=length - 1)
        if (cursor_year, cursor_month) == (year, month):
            return start, end
        start = end + datetime.timedelta(days=1)
        cursor_year, cursor_month = _next_month(cursor_year, cursor_month)
