"""add plaid sync cursor to accounts

Revision ID: 2ca9cd3f2e6a
Revises: 4948ef0c52b6
Create Date: 2026-07-20 05:06:07.065970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ca9cd3f2e6a'
down_revision = '4948ef0c52b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('plaid_sync_cursor', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'plaid_sync_cursor')
    # ### end Alembic commands ###
